### ISSUE TITLE
Why ```HDFCatalog.to_mesh``` generate negative values for the density field 'delta+1'?

### ISSUE THREAD

**Issue by WangYun1995** [sjforeman/bskit#1]
By using Nbodykit, I want to generate a mesh of 1024^3 grids from the discrete particles of TNG100 simulation.

``` 
in_mesh = HDFCatalog.to_mesh(Nmesh=1024,BoxSize=75,dtype='f8', interlaced=True, 
                                compensated=True, resampler='cic', position='Coordinates',weight='Masses')
```

However, I find that there are many negative values, which is wrong because that delta+1>=0.
Did this happen to you?

How to fix this issue?

**Comment by sjforeman** [comment]
This is being discussed in https://github.com/bccp/nbodykit/issues/676, so I'll close this issue
